route:
  receiver: 'mail'
  repeat_interval: 4h
  group_by: [ alertname ]


receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'smpt_server:1025'
        from: 'dev0psgyus@monitor.net'
        to: 'alertmanger@gmonitor.net'